---
- name: Ensure Python3 and pip are installed
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Install Python dependencies for Docker
  pip:
    name:
      - requests
      - docker
    state: present
    executable: pip3
  become: yes

- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Pull Docker image from Docker Hub
  docker_image:
    name: "trsnich/my-python-app:{{ image_tag }}"
    source: pull
  become: yes

- name: Deploy Docker container
  docker_container:
    name: my-python-app
    image: "trsnich/my-python-app:{{ image_tag }}"
    state: started
    restart_policy: always
    ports: "{{ app_port }}:80"
  become: yes