name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Авторизуемся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Собираем и пушим Docker-образ
      - name: Build and push Docker image
        run: |
          docker build -t trsnich/my-python-app:latest .
          docker push trsnich/my-python-app:latest

      # 5. Устанавливаем Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # 6. Сканируем образ на уязвимости с помощью Trivy
      - name: Scan image for vulnerabilities
        run: |
            trivy image --exit-code 0 --severity HIGH,CRITICAL trsnich/my-python-app:latest